# Generated by Django 5.0.6 on 2024-06-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20)),
                ('soyad', models.CharField(max_length=20)),
                ('unvan', models.CharField(max_length=50)),
                ('nomre', models.CharField(max_length=20)),
                ('tehsil', models.CharField(max_length=50)),
                ('tecrubeleri', models.TextField()),
                ('bacariqlari', models.TextField()),
                ('hobbi', models.TextField()),
                ('dil_bilikleri', models.CharField(max_length=50)),
                ('is_yeri', models.TextField()),
            ],
        ),
    ]

    